version: '2'

networks:
  wewo-net:
    driver: bridge

services:
  app:
    build: ./app/
    container_name: app
    # restart: always
    image: wewo/app
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - user-service
      - note-service
      - graph-service
    tty: true
    networks:
      - wewo-net
  user-service:
    build: ./user_service/
    container_name: user-service
    # restart: always
    image: wewo/user-service
    ports:
      - "3001:3001"
    expose:
      - "3001"
    tty: true
    depends_on:
      - user-mongodb
    networks:
      - wewo-net
  note-service:
    build: ./note_service/
    container_name: note-service
    # restart: always
    image: wewo/note-service
    ports:
      - "3002:3002"
    expose:
      - "3002"
    tty: true
    depends_on:
      - note-mongodb
    networks:
      - wewo-net
  graph-service:
    build: ./graph_service/
    container_name: graph-service
    # restart: always
    image: wewo/graph-service
    ports:
      - "3003:3003"
    expose:
      - "3003"
    tty: true
    depends_on:
      - graph-mongodb
    networks:
      - wewo-net
  image-hosting:
    build: ./image_hosting/
    container_name: image-hosting
    # restart: always
    image: wewo/image-hosting
    ports:
      - "3004:3004"
    expose:
      - "3004"
    tty: true
    depends_on:
      - image-hosting-minio
    networks:
      - wewo-net
  user-mongodb:
    container_name: user-mongodb
    # restart: always
    image: mongo
    ports:
      - "4001:27017"
    expose:
      - "27017"
    tty: true
    networks:
      - wewo-net
  note-mongodb:
    container_name: note-mongodb
    # restart: always
    image: mongo
    ports:
      - "4002:27017"
    expose:
      - "27017"
    tty: true
    networks:
      - wewo-net
  graph-mongodb:
    container_name: graph-mongodb
    # restart: always
    image: mongo
    ports:
      - "4003:27017"
    expose:
      - "27017"
    tty: true
    networks:
      - wewo-net
  image-hosting-minio:
    container_name: image-hosting-minio
    # restart: always
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: 12345678
    command: ["server", "/data", "--console-address", ":9001"]
    ports:
      - "4004:9000"
      - "4005:9001"
    expose:
      - "9000"
      - "9001"
    tty: true
    networks:
      - wewo-net
